#!/run/current-system/sw/bin/env sh
fav_vids="/home/yannick/Videos/favorites"

mkdir -p $fav_vids
rm -f ${fav_vids}/*

favorites=( "/Mobility" )
for f in "${favorites[@]}"
do
  for vid in /home/yannick/Videos/${f}/*
  do
    ln -s "${vid}" "${fav_vids}"
  done
done
