#!/run/current-system/sw/bin/env sh
base_folder_path="/home/yannick/Videos"
fav_vids="${base_folder_path}/favorites"

mkdir -p $fav_vids
rm -f ${fav_vids}/*

favorites=( "/Mobility" )
for f in "${favorites[@]}"
do
  for vid in /home/yannick/Videos/${f}/*
  do
    ln -s "${vid}" "${fav_vids}"
  done
done
